version: '3.9'

services: #informações dos documentos retirados do Docker Hub
  db: #o nome de sua escolha, que sera o banco de dados
    image: postgres
    restart: always #em caso de problemas ele restarta sozinho
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: imagelite
    ports: #portas oficiais do docker
      - '5432:5432'
    volumes: #espelhar arquivos dentro do container na pasta do computador
      - ./data:/var/lib/postgresql/data

  pgadmin:  #nome do acesso
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
    ports:
      - '15432:80'
    depends_on: db #Depende do que? para usar o cliente tem que subir o DB